### ISSUE TITLE
can we code something that download video from youtube? 

### ISSUE THREAD

**Issue by ytbryan** [cseddie/cseddie.github.io#11]

**Comment by cseddie** [comment]
Is this for the next lesson?

**Comment by ytbryan** [comment]
probably. One of the next few lessons

**Comment by ytbryan** [comment]
how to get this video? https://www.youtube.com/watch?v=qgQGUquxOVE

to appear like => [this](https://r2---sn-npoe7n7y.googlevideo.com/videoplayback?mime=video/mp4&requiressl=yes&clen=11236033&source=youtube&sparams=clen,dur,ei,expire,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn&ip=138.75.142.195&lmt=1417207135405630&upn=-sNAbDhMCTM&id=o-ADHP2EB0-T5YKg7Unp_Duy3RZooaqEkhZwIOvRzQIoni&ei=sj-sWIvVBIO0oQOKipbYCw&key=cms1&ratebypass=yes&pl=18&expire=1487705106&dur=188.522&gir=yes&signature=1364F0A3BB8C9A186BAD0EC072CA878059B6A1FF.6EB9929A58433531536D58A9730D382261324079&ipbits=0&itag=18&title=Jake%20Gyllenhaal%20Said%20WHAT%20About%20Hugh%20Jackman&redirect_counter=1&cm2rm=sn-hvcpaxvox-npo67l&req_id=c2372277ed29a3ee&cms_redirect=yes&mm=30&mn=sn-npoe7n7y&ms=nxu&mt=1487683416&mv=m)

And eventually download it onto your computer?

And what's the difference between the above video and this video? 
https://www.youtube.com/watch?v=CcEJ10Z8JJA (hint: I can't seems to derive the video source of this video)

**Comment by cseddie** [comment]
From what I know, the difference between the 2nd video and the last video is that the 2nd is downloaded while the 3rd is not.

But i thought we can't download video from YouTube????

**Comment by ytbryan** [comment]
can, we will try next lesson for educational purpose

**Comment by cseddie** [comment]
Okok👍

**Comment by cseddie** [comment]
Oh ya and one more thing, the difference between the two is their url, for the second one the URL is totally different, "http://r2---bla bla bla" the second video we can see that the source of the video is from YouTube.

**Comment by ytbryan** [comment]
```
require "open-uri"

File.open('pie.mp4', 'wb') do |fo|
  fo.write open("https://r3---sn-npoeen7d.googlevideo.com/videoplayback?sparams=clen,dur,ei,expire,gir,id,initcwndbps,ip,ipbits,itag,lmt,mime,mm,mn,ms,mv,pl,ratebypass,requiressl,source,upn&lmt=1429529178742606&gir=yes&ei=79SyWJ6HG-f8oQPRp4K4Dg&source=youtube&pl=19&ip=138.75.142.195&mime=video/mp4&requiressl=yes&expire=1488136527&id=o-ABjWNvNhJKIbAKI3Q8EHSkBBQgGvy92apgCKBkVd3EKU&ipbits=0&ratebypass=yes&key=cms1&upn=lLvJ1PSyayw&itag=18&clen=21482507&signature=429B2F0075B89924BC9C40FFD79E83A5609EDA0E.3509D31C3995D905A8A6259F354CD9EECB8B604C&dur=478.052&title=I%20GOOGLED%20MYSELF&cm2rm=sn-hvcpaxvox-npos7e,sn-npols7s&req_id=2015855d6c30a3ee&redirect_counter=2&cms_redirect=yes&mm=43&mn=sn-npoeen7d&ms=onl&mt=1488114962&mv=m").read
end

```

**Comment by cseddie** [comment]
You want me to create a new file and paste this in to try downloading video is it?

**Comment by ytbryan** [comment]
nope, i paste here so that i can delete the file on my desktop. This is for
next lesson.

**Comment by cseddie** [comment]
Ok👍
